config/routes.rb
Rails.application.routes.draw do
  root 'posts#title'

  # Table 라우팅
  get 'tables/index/:user_id' => 'tables#index', as: "tables"

  get 'tables/mypage'

  post 'tables/comments/create/:user_id' => 'tables#comment_create', as: "tables_comments_create"

  # Devise controller 관련 라우팅
  devise_for :users, controllers: { registrations: 'users/registrations', passwords: 'users/passwords', sessions: 'users/sessions' }

  #search 관련 라우팅
  get 'posts/search'
  get :search, controller: :posts
  



  # Post(화장품등록) 관련 라우팅 (REST)
  resources :posts do
    member do
      get :get_middle_categories, defaults: { format: "js" }
      get :get_small_categories, defaults: { format: "js" }
    end
  end

  # like 관련 라우팅
  post 'post/:post_id/like' => 'likes#like_toggle'

  

  # 친구 기능 라우팅  
  resources :friend_requests
  get 'friends/index'
  delete 'friends/destroy/:id' => 'friends#destroy', :as => 'friends_destroy'
  




end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/post.rb
class Post < ApplicationRecord
	mount_uploader :carrierimage, ImageUploader

	belongs_to :user
	has_many :likes
	has_many :liked_users, through: :likes, source: :user


  # 화장품명,  DB에 저장X
  validates :title, :category, :open_date, :exp_date, :public, :carousel, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:title]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  before_action :force_json, only: :autocomplete

  layout 'for_edit_layout', only: [:edit]

  def title
  end

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @post = Post.new

    #깃에서 지워주세욥 @items = Post.where(["title LIKE ?","%#{params[:search]}%"])
    #이것도! @usersearch = User.where(["nickname LIKE ?","%#{params[:search]}%"])
  end

  # GET /posts/1
  # GET /posts/1.json
  # D-day 보여주는 액션
  def show
    @exp_date = @post.exp_date
    @today = Date.today
    @remain = (@exp_date - @today).to_i
    @sign = '-'
    if @remain <= 0
      @result = "사용기한 끝! 쓰지마세요!"
      @remain = -@remain
      @sign = '+'
    elsif @remain <= 10
      @result = "10일 이내"
    elsif @remain <= 20
      @result = "10일~20일"
    elsif @remain <= 30
      @result = "20일~30일"
    elsif @remain <= 40
      @result = "30일~40일"
    elsif @remain <= 50
      @result = "40일~50일"     
    else
      @result = "안전함(50일 이상)"
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  def get_middle_categories
    @middle_categories = Category.find(params[:category_id]).children
  end

  def get_small_categories
    @small_categories = Category.find(params[:category_id]).children
  end

  # GET /posts/1/edit
  def edit
    @cate_id = @post.category
    @cate = Category.find(@cate_id)
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to tables_path(current_user), notice: '화장품 등록 완료!' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to tables_path(current_user), notice: '화장품 수정 완료!' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to tables_path(current_user), notice: '화장품 삭제 완료!' }
      format.json { head :no_content }
    end
  end

   def search
      @items = Post.where(["title LIKE ?","%#{params[:mySearch]}%"])
      @usersearch = User.where(["nickname LIKE ?","%#{params[:mySearch]}%"])
      @post = Post.new
      
    end 

    # def autocomplete
    #   @items = Post.where(["title LIKE ?","%#{params[:search]}%"]).limit(5)

    # end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :memo, :img_url, :category, :open_date, :exp_date, :carousel, :public, :user_id, :carrierimage)
    end

    def force_json
      request.format = :json
    end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/get_middle_categories.js.erb
<% if @middle_categories.blank? %>
	$('#middle-select').attr('disabled', true);
	$('#middle-select').hide();
<% else %>
	$('#middle-category').html("<%= j collection_select(:post, :category, @middle_categories, :id, :name, {:prompt => "중분류"}, {:id => "middle-select", :required => true}) %>");
<% end %>

app/views/posts/get_small_categories.js.erb
<% if @small_categories.blank? %>
	$('#small-select').attr('disabled', true);
	$('#small-select').hide();
<% else %>
	$('#small-category').html("<%= j collection_select(:post, :category, @small_categories, :id, :name, {prompt: '소분류'}, {:id => 'small-select', :required => true}) %>");
<% end %>

app/views/posts/index.html.erb
<nav class="navbar navbar-dark bg-dark" style='height: 80px;'>
  <div class='headingpouch'>
    <a class="navbar-brand" href="#">Pouch Mate</a>
  </div>
</nav> 

<!-- The Modal -->
<div id="myModal1" class="modal1">
<!-- Modal content -->
  <div class="modal-content1">
    <div class="ctn-form">
    <%= render 'form', post: @post %>
    </div>
  </div>                        
</div>
<br>

<!--카루셀 화장대-->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval="10000">
  <div class="carousel-inner">
    <div class="carousel-item active">
        <div class='firstpage'>
          <div class='top'>
            <div class='item left'>
              <div class='floor one'>
                <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
              </div>
              <div class='floor two'>
                <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
              </div>
            </div>
            <div class='item middle'>
                    <div class='aaa'>
                        <div class='bbb'>
                            <% if user_signed_in? %>
                                <a href='/friends/index'><img src='/like.png'></a>
                            <% end %>
                        </div>
                    </div>
                    <div class="profile"'>
                      <img src='/user.png' class='profileimage'>
                    </div><br>
                    <div class="profile_info">
                        <h1>
                            <%= @nickname %>
                            유정
                        </h1>
                    </div>
                    <br>
                    <div class='wrapwrap'>
                      <div class='friendsandlifetem'>
                              <% if user_signed_in? %>
                                  <a href='/friends/index'><img src='/friends_icon.png'></a>
                              <% end %>                        
                      </div>
                      <div id="myBtn1"><img src='/plus.png'></div>
                    </div>
            </div>
            <div class='item right'>
              <div class='floor three'>
                <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
              </div>
              <div class='floor four'>
                <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>                
                <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
                <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>    
                <div class="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>             
              </div>
            </div>
          </div>
          <div class='bottom'>
            <div class='floor five'>
                <% @posts.each_with_index do |p,index| %>
                  <div class="box boxdrag <%=index%>" ondrop="drop(event)" ondragover="allowDrop(event)">
                    <a href='/posts/<%=p.id%>'>
                      <img src="<%= p.carrierimage.thumb.url %>" draggable="true" ondragstart="drag(event)" id='drag <%=index%>' class="imagedrag">
                    </a>
                  </div>
                <%end%>              
            </div>
          </div>
        </div>
    </div>
    <div class="carousel-item rightside">
        <div class='firstpage'>
          <div class='top'>
            <div class='pageright'>
              <div class='topright floorside'></div>
              <div class='middleright floorside'></div>
            </div>
          </div>
          <div class='bottom'>
            <div class='bottomright floorside'></div>
          </div>
        </div>      
    </div>
    <div class="carousel-item leftside">
        <div class='firstpage'>
          <div class='top'>
            <div class='pageright'>
              <div class='topleft floorside'> 
              </div>
              <div class='topleft floorside'></div>
            </div>
          </div>
          <div class='bottom'>
            <div class='bottomleft floorside'></div>
          </div>
        </div>      
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev" style="width: 5%;opacity: 0.01;">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next" style="width: 5%;opacity: 0.01;">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class='footer'>

  <div class='comment_div'>
    <div class='comment_title'>
      <p>파우치 리뷰</p><br>
    </div>


<%= link_to 'New Post', new_post_path %>
<!-- 이제 모달 띠울꼬얌- by재인 -->
\
<!-- Trigger/Open The Modal -->
<div id="myBtn">등록하기</div>
                
<!-- The Modal -->
<div id="myModal" class="modal">
    <!-- Modal content -->
    <div class="modal-content">
      <div class="ctn-form">
        <%= render 'form', post: @post %>

    <div class='comment_content'>
      <div class='comment_profile'><img src='/user.png' class='commentprofileimage'></div>
      <div class='comment_comment'>
        <p>다은 재인아 DHC 클렌징 오일 어때?</p>
        <p>4주 답글달기</p>

      </div>
    </div>
  </div>

  <div class='friends_div'>인생템</div>
</div>
<div class='daeun'>
   <%= form_tag("/posts/search", method: "get") do %>
        <%= text_field_tag(:search,params[:search]) %>
        <%= submit_tag "검색", :name => nil %>
    <% end %>

    
</div>
<%= link_to '친구기능(friend_requests/index)', friend_requests_path %>

    <script type='text/javascript'>
        // Get the modal
        var modal1 = document.getElementById('myModal1');
        
        // Get the button that opens the modal
        var btn1 = document.getElementById("myBtn1");
        
        // Get the <span> element that closes the modal
        var span = document.getElementsByClassName("close")[0];
        
        // When the user clicks the button, open the modal 
        btn1.onclick = function() {
            modal1.style.display = "block";
        }
        
        // When the user clicks on <span> (x), close the modal
        span.onclick = function() {
            modal1.style.display = "none";
        }
        
        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function(event) {
            if (event.target == modal1) {
                modal1.style.display = "none";
            }
        }        
    </script>

    <!-- 이건 드래그앤드롭 자바 스크립인임 -재인 -->
     <script>
    function allowDrop(ev) {
        ev.preventDefault();
    }

    function drag(ev) {
        ev.dataTransfer.setData("text", ev.target.id);
    }

    function drop(ev) {
        ev.preventDefault();
        var data = ev.dataTransfer.getData("text");
        ev.target.appendChild(document.getElementById(data));
    }
    </script>

app/views/posts/new.html.erb
<h1>새로운 화장품 등록하기</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>


<%= javascript_include_tag('cosmetic_new') %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @post.memo %>
</p>

<div class='testest'>
  <strong>carrierimage:</strong>
  <img src='<%= @post.carrierimage.thumb %>'>
</div>

<p>
  <strong>Category:</strong>
  <%= @post.category %>
</p>

<p>
  <strong>Open date:</strong>
  <%= @post.open_date %>
</p>

<p>
  <strong>Exp date:</strong>
  <%= @post.exp_date %>
</p>

<p>
  <strong>Public:</strong>
  <%= @post.public %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<p>
  <strong>D-day 테스트용</strong>
  </br>
  exp_date : <%= @exp_date %>
  </br>
  today : <%= @today %>
  </br>
  D<%= @sign %><%= @remain %>
  </br>
  결과 : <%= @result %>
</p>

<!------다은 좋아요 기능 ---------------->
<p>
  <strong>Like:</strong>
  <%= @post.likes.size %> 명이 좋아합니다. 
</p>
 
<p>
  <% if current_user.is_like? (@post) %>
  <%=form_tag("/post/#{@post.id}/like") do%>
  <button> 좋아요 취소 </button>  
  <%end%>
  
  <% else %>
  <%=form_tag("/post/#{@post.id}/like") do%>
  <button> 좋아요 </button>  
  <%end%>
  
  <% end %>
</p>
<!------다은 좋아요 기능 ----------------->

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', tables_path(user_id: current_user.id) %>

app/views/posts/title.html.erb

<style>

    .jnav, .application_login_info{
      display: none;
    }

    .modal-content{
        background-color: #333333;
        background-color: rgba( 51, 51, 51, 0.95 );
    }
    
    form {
      text-align: center;
    }
    

    /*여기가 modal css*/
    label {
      display: block;
      letter-spacing: 4px;
      padding-top: 30px;
      text-align: center;
    }
    label .field {
      color: #9B9B9B;
      cursor: text;
      font-size: 24px;
      line-height: 20px;
      text-transform: uppercase;
      -moz-transform: translateY(-34px);
      -ms-transform: translateY(-34px);
      -webkit-transform: translateY(-34px);
      transform: translateY(-50px);
      transition: all 0.3s;
    }
    input#titleSignupModal {

      background-color: transparent;
      border: 0;
      border-bottom: 2px solid #4A4A4A ;
      color: white;
      font-size: 24px;
      font-family: 'Gothic A1', sans-serif;
      letter-spacing: -1px;
      outline: 0;
      padding: 5px 20px;
      text-align: center;
      transition: all 0.3s;
      width: 200px;
    }
    label input:focus {
      max-width: 100%;
      width: 400px;
    }
    label input:focus + .field {
      color: #F0F0F0;
      font-size: 13px;
      -moz-transform: translateY(-74px);
      -ms-transform: translateY(-74px);
      -webkit-transform: translateY(-74px);
      transform: translateY(-74px);
    }
    label input:valid + .field {
      font-size: 13px;
      -moz-transform: translateY(-74px);
      -ms-transform: translateY(-74px);
      -webkit-transform: translateY(-74px);
      transform: translateY(-74px);
    }
    
    button {
      background-color: #333333;
      border: 2px solid white;
      border-radius: 15px;
      color: white;
      cursor: pointer;
      font-size: 15px;
      margin-top: 15px;
      padding: 10px 23px;
      text-transform: uppercase;
      transition: all 200ms;
    }
    button:hover, button:focus {
      background-color: white;
      color: #333333;}

/*두번쨰*/

@import url(https://fonts.googleapis.com/css?family=Exo:100,200,400);
@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:700,400,300);

body {
  margin: 0;
  padding: 0;
  background: #fff;

  color: #fff;
  font-family: Arial;
  font-size: 12px;
}

.body {
  position: absolute;
  top: -20px;
  left: -20px;
  right: -40px;
  bottom: -40px;
  width: auto;
  height: auto;
  -webkit-filter: blur(5px);
  z-index: 0;
}

.grad {
  position: absolute;
  top: -20px;
  left: -20px;
  right: -40px;
  bottom: -40px;
  width: auto;
  height: auto;
  background: -webkit-gradient(
    linear,
    left top,
    left bottom,
    color-stop(0%, rgba(0, 0, 0, 0)),
    color-stop(100%, rgba(0, 0, 0, 0.35))
  ); /* Chrome,Safari4+ */
  z-index: 1;
  opacity: 0.7;
}

.header {
  position: absolute;
  top: calc(50% - 35px);
  left: calc(50% - 255px);
  z-index: 2;
}

.header div {
  float: left;
  color: #fff;
  font-family: "Exo", sans-serif;
  font-size: 35px;
  font-weight: 500;
}

.header div span {
  font-size: 18px; 
  line-height: 100%;
}


.login {
  position: absolute;
  top: calc(50% - 75px);
  left: calc(50% - 50px);
  height: 150px;
  width: 350px;
  padding: 10px;
  z-index: 2;
  padding-right: 100px;;
}

.login input[type="text"], .login input[type='email'] {
  width: 250px;
  height: 30px;
  background: transparent;
  border: 1px solid rgba(255, 255, 255, 0.6);
  border-radius: 2px;
  color: #fff;
  font-family: "Exo", sans-serif;
  font-size: 16px;
  font-weight: 400;
  padding: 4px;
}

.login input[type="password"] {
  width: 250px;
  height: 30px;
  background: transparent;
  border: 1px solid rgba(255, 255, 255, 0.6);
  border-radius: 2px;
  color: #fff;
  font-family: "Exo", sans-serif;
  font-size: 16px;
  font-weight: 400;
  padding: 4px;
  margin-top: 10px;
}

.login input[type="submit"] {
  width: 250px;
  height: 35px;
  background: #fff;
  border: 1px solid #fff;
  cursor: pointer;
  border-radius: 2px;
  color: #a18d6c;
  font-family: "Exo", sans-serif;
  font-size: 16px;
  font-weight: 400;
  padding: 6px;
  margin-top: 10px;
}

.login input[type="submit"]:hover {
  opacity: 0.8;
}

.login input[type="submit"]:active {
  opacity: 0.6;
}

.login input[type="text"]:focus {
  outline: none;
  border: 1px solid rgba(255, 255, 255, 0.9);
}

.login input[type="password"]:focus {
  outline: none;
  border: 1px solid rgba(255, 255, 255, 0.9);
}

.login input[type="submit"]:focus {
  outline: none;
}

::-webkit-input-placeholder {
  color: rgba(255, 255, 255, 0.6);
}

::-moz-input-placeholder {
  color: rgba(255, 255, 255, 0.6);
}

/*재인이가 추가한다 스타일*/
#user_profile_img{
  font-size: 10px;
  padding-left: 40%;
  padding-top: 10px;
}
.jgender{
  display: flex;
  padding-left: 38%;  
}
</style>

<body_mypage>
    <video id="bgvid" playsinline autoplay muted loop>
      <!--- Video needs to be muted, since Chrome 66+ will not autoplay video with sound.
    WCAG general accessibility recommendation is that media such as background video play through only once. Loop turned on for the purposes of illustration; if removed, the end of the video will fade in the same way created by pressing the "Pause" button  -->
    <source src="/Webcosmetic.mp4" type="video/mp4">
</body_mypage>

<!--로그인 창-->
<link href="https://fonts.googleapis.com/css?family=Gothic+A1" rel="stylesheet">

<div class="body"></div>
<div class="grad"></div>
<div class="header" style='line-height:25px'>
    <div>Pouch Mate<br><span>너와 나의 파우치 메이트</span></div>
</div>
    <br>

    <!--로그인 창 -->
<div class="login">
<%= form_tag(new_user_session_path) do %>
      <input type="text" placeholder="E-Mail" name="user[email]"><br>
      <input type="password" placeholder="password" name="user[password]"><br>
      <input type="submit" value="Login">
<% end %> 

     <!--  <input type="text" placeholder="E-Mail" name="email"><br>
      <input type="password" placeholder="password" name="password"><br>
      <input type="button" value="Login"> -->
      


      <!-- a tag trigger modal -->
            <a data-toggle="modal" href="#exampleModalCenter" style='color:White' data-backdrop="false">회원가입하기</a>
            <% if user_signed_in? %>
              <%= link_to "내 화장대로 이동(테스트링크)", tables_path(user_id: current_user.id) %> 
            <% end %>

            
            <!-- Modal -->
            <div class="modal" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document" >
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalCenterTitle" style='color:white'>회원가입</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close" justify-content='right'>
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  
                  <!------------------------------------->
                  <div class="modal-body">
                   <!--  <form>
                      <label>
                        <input type="text" id='titleSignupModal' required />
                        <div class="field" >이름</div>
                      </label>

                      <label id='titleSignupModal-label'>

                      <label>

                        <input type="number" required />
                        <div class="field" >나이</div>
                      </label>

                      <label id='titleSignupModal-label'>

                      <label>

                        <input type="text" id='titleSignupModal' required />
                        <div class="field" >E-Mail</div>
                      </label>

                      <label id='titleSignupModal-label'>

                      <label>

                        <input type="text" id='titleSignupModal' required />
                        <div class="field" >닉네임</div>
                      </label>
                      <button>Submit</button>
                    </form>
                     -->

<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <label>

  <div class="field" id='titleSignupModal'>
    <%= f.label :"이메일" %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "off" %>
  </div>



  <div class="field" id='titleSignupModal'>
    <%= f.label :"이름" %><br />
    <%= f.text_field :username, autofocus: true, autocomplete: "off"  %>
  </div>
  
  <div class="field" id='titleSignupModal'>
    <%= f.label :"닉네임" %><br />
    <%= f.text_field :nickname, autofocus: true, autocomplete: "off"  %>
  </div>

  <div class="field" id='titleSignupModal'>
    <%= f.label :"프로필 사진" %>
    <%= f.file_field :profile_img %>
  </div>

  <div class="field" id='titleSignupModal'>
    <%= f.label :"나이" %>
    <%= f.select :age, options_for_select(10..99) %>
  </div>
  
  <div class="field" id='titleSignupModal'>
    <%= f.label :"성별" %>
    <div class='jgender'>
      <div class='male'>
        <%= label_tag(:gender, "남자") %>
        <%= f.radio_button(:gender, "남자", :checked => true) %>      
      </div>
      <div class='female'>
        <%= label_tag(:gender, "여자") %>
        <%= f.radio_button(:gender, "여자") %>      
      </div>
    </div>
  </div>

  <div class="field" id='titleSignupModal'>
    <%= f.label :"한줄소개" %>
    <%= f.text_field :intro, autocomplete: "off" %>
  </div>
  
  <div class="field" id='titleSignupModal'>
    <%= f.label :"비밀번호" %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %>자 이상)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field" id='titleSignupModal'>
    <%= f.label :"비밀번호 확인" %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  
  <div>
    <%= f.hidden_field :admin %>
  </div>
</label>
  <div class="actions">
    <%= hidden_field_tag :redirect_to, params[:redirect_to] %>
    <%= f.submit "회원가입" %>
  </div>
<% end %>


                        
                  </div>
                </div>
              </div>
            </div>
      
<div>
      
<!-- * 로그인 안하면 화장대 못들어감 * 타이틀에서 밑으로 스크롤 하면 견본화장대 구경 가능 -->
<br>




<!----자바스크립트 -->


<script type='text/javascript'>
    var vid = document.getElementById("bgvid");
    var pauseButton = document.querySelector("#polina button");
    
    if (window.matchMedia('(prefers-reduced-motion)').matches) {
        vid.removeAttribute("autoplay");
        vid.pause();
        pauseButton.innerHTML = "Paused";
    }
    
    function vidFade() {
      vid.classList.add("stopfade");
    }
    
    vid.addEventListener('ended', function()
    {
    // only functional if "loop" is removed 
    vid.pause();
    // to capture IE10
    vidFade();
    }); 
    
    
    pauseButton.addEventListener("click", function() {
      vid.classList.toggle("stopfade");
      if (vid.paused) {
        vid.play();
        pauseButton.innerHTML = "Pause";
      } else {
        vid.pause();
        pauseButton.innerHTML = "Paused";
      }
    })

</script>