config/routes.rb
Rails.application.routes.draw do
  root 'posts#title'

  # Table 라우팅
  get 'tables/index/:user_id' => 'tables#index', as: "tables"

  get 'tables/mypage'

  post 'tables/comments/create/:user_id' => 'tables#comment_create', as: "tables_comments_create"

  # Devise controller 관련 라우팅
  devise_for :users, controllers: { registrations: 'users/registrations', passwords: 'users/passwords', sessions: 'users/sessions' }

  #search 관련 라우팅
  get 'posts/search'
  get :search, controller: :posts
  



  # Post(화장품등록) 관련 라우팅 (REST)
  resources :posts do
    member do
      get :get_middle_categories, defaults: { format: "js" }
      get :get_small_categories, defaults: { format: "js" }
    end
  end

  # like 관련 라우팅
  post 'post/:post_id/like' => 'likes#like_toggle'

  

  # 친구 기능 라우팅  
  resources :friend_requests
  get 'friends/index'
  delete 'friends/destroy/:id' => 'friends#destroy', :as => 'friends_destroy'
  




end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pouchmate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Required meta tags 부트스트랩홈페이지 카루셀-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS 카루셀-->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>    
  </head>

  <body>
    <nav class="jnav" style='height: 90px;'>
      <div class='headingpouch'>
        <% if user_signed_in? %>
          <%= link_to 'Pouch Mate', tables_path(current_user.id), {:class => 'jnavbar_brand'} %>
        <% end %>
      </div>
      <div class="cntr-innr">
        <label class='search' for='inpt_search'>
          <form id='inpt_search' autocomplete="off" action="/posts/search">
            <div class="autocomplete janesearch" style="width:300px;">
              <input id="inpt_search" type="text" name="mySearch" >
              <input type="submit" class='janesubmit'>
            </div>
            
          </form>
        </label>  
      </div> 
    </nav>   

    <% if notice %>
      <p id="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p id="alert"><%= alert %></p>
    <% end %>      
    <%= yield %>

    <div class='application_login_info'>
      <p>★파우치 메이트★
        </br>
        <% if user_signed_in? %>
          <%= current_user.email %>
          <%= link_to "회원정보수정", edit_user_registration_path %>
          <%= link_to "로그아웃하기", destroy_user_session_path %>
        <% else %>
          <%= link_to '로그인', new_user_session_path %>
          <%= link_to '회원가입', new_user_registration_path %>
        <%end%>
      </p>
    </div>

    <!-- 검색 자바 -->
    <script type="text/javascript">
      $("#inpt_search").on('focus', function () {
        $(this).parent('label').addClass('active');
    });
    $("#inpt_search").on('blur', function () {
        if($(this).val().length == 0)
            $(this).parent('label').removeClass('active');
    });
    </script>
  </body>
  
</html>

app/views/layouts/for_edit_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pouchmate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Required meta tags 부트스트랩홈페이지 카루셀-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS 카루셀-->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>    
  </head>

  <body>
    <nav class="jnav" style='height: 90px;'>
      <div class='headingpouch'>
        <%= link_to 'Pouch Mate', tables_path(current_user.id), {:class => 'jnavbar_brand'} %>
        <!-- <a class="jnavbar_brand" href="#">Pouch Mate</a> -->
      </div>
      <div class="cntr-innr">
        <div class='search'>
          <%= form_tag("/posts/search", method: "get") do %>
            <%= text_field_tag(:search,params[:search], data: {behavior:"autocomplete"}) %>
          <% end %>
        </div>  
      </div> 
    </nav>
    <% if notice %>
      <p id="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p id="alert"><%= alert %></p>
    <% end %>      
    <%= yield %>

    
  </body>
</html>